### ISSUE TITLE
[ERROR] The redirect uri included is not valid.

### ISSUE THREAD

**Issue by ykoh42** [innovationacademy-kr/42oauth#2]
안녕하세요!

`42 OAuth`를 이용해보고자 깃 클론을 받아 테스트해보고 있는데 아래와 같은 문제가 발생하여 제보 드립니다!

# 문제 상황

`README.md` 파일에 있는

```
Register an app on 42 intra and set the redirect URI to http://127.0.0.1/login/42/return.
```

내용대로 42app에서 `REDIRECT URI`를 지정하였는데,  아래와 같은 에러가 발생하였습니다.

![Screen Shot 2021-07-20 at 1 44 45 AM](https://user-images.githubusercontent.com/16534576/126196525-5bef1a34-1c0e-4135-bc51-a3a7ad00341a.png)

# 해결 방법
`REDIRECT URI`를 `http://localhost:3000/login/42/return`로 변경하였더니 정상적으로 작동하였습니다.

관련하여 `README.md` 파일에 `PR`도 남기도록 하겠습니다!

---

좋은 예제를 제공해주셔서 감사합니다!

**Comment by kenu** [comment]
감사합니다. :)
